### ISSUE TITLE
SBT signaling standard

### ISSUE THREAD

**Issue by TimDaub** [agoraxyz/guild-pin-contract#9]
hi,

I came across your Guild Pin product and thought it was really cool. I‘m the author of https://eips.ethereum.org/EIPS/eip-5192 and we suggest to implement events for locking and unlocking tokens, as well as a locked function to get the status of a token‘s lock.

From what I can tell, your implementation reverts on all transferring functions, which is also what we suggest doing in the standard.

Although our standard allows unlocking tokens again, you don‘t have to implement that. 

Our main idea is that by emitting the Lock and Unlock events and through the interface identifier, we can let wallets know when a token is soulbound, such that they can hide the transfer button, and inform the user about non-transferability.

E.g. OpenSea added partial support for this and the more people we can convince of adding these two events and the view function, the more the value if SBTs can grow 🤞

Hope I could sell you on this standard! It‘s far from perfect, but it could help grow the space a little!

![IMG_3985](https://github.com/agoraxyz/guild-pin-contract/assets/2758453/3d5b94e5-dbcb-4ab5-a056-c2fc62560fee)

happy to answer any questions or even help implementing! Just text me

best,
Tim

**Comment by TomiOhl** [comment]
Hey @TimDaub, thanks for introducing me to this (and for the eip itself ofc)!
I've implemented it in #10, could you review it please?
